# Generated by Django 3.1.4 on 2020-12-08 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('CuNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='课程编号')),
                ('CuName', models.CharField(max_length=50, verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='homework',
            fields=[
                ('HomNo', models.IntegerField(primary_key=True, serialize=False, verbose_name='作业id')),
                ('Title', models.CharField(default='a', max_length=50, verbose_name='作业标题')),
                ('PubDate', models.DateField(default=django.utils.timezone.now, verbose_name='发布日期')),
                ('CuNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.course', verbose_name='课程编号')),
            ],
            options={
                'ordering': ['-PubDate'],
            },
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('MaNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='管理员编号')),
                ('MaName', models.CharField(max_length=50, verbose_name='管理员姓名')),
                ('MaPassWord', models.CharField(default='123456', max_length=16, verbose_name='管理员密码')),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('SignNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='签到编号')),
                ('StuNo', models.CharField(max_length=50, verbose_name='学生学号')),
                ('PubTime', models.DateTimeField(verbose_name='发布时间')),
                ('SubTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='签到时间')),
                ('CuNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.course', verbose_name='课程编号')),
            ],
            options={
                'verbose_name': '签到',
                'verbose_name_plural': '签到',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('StuNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='学生学号')),
                ('StuName', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('StuSex', models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=30, null=True, verbose_name='学生性别')),
                ('Major', models.CharField(max_length=50, null=True, verbose_name='专业名称')),
                ('StuPassWord', models.CharField(default='123456', max_length=16, verbose_name='学生密码')),
                ('CuNo', models.ManyToManyField(related_name='students', to='job.course', verbose_name='学生选修的课程编号')),
                ('need_to_sign', models.ManyToManyField(related_name='students', to='job.sign', verbose_name='需要进行此次签到的学生')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['-Major', 'StuNo'],
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('TeaNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='教师编号')),
                ('TeaName', models.CharField(max_length=50, verbose_name='教师姓名')),
                ('TeaSex', models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=30, null=True, verbose_name='教师性别')),
                ('TeaPassWord', models.CharField(default='123456', max_length=16, verbose_name='教师密码')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'ordering': ['-TeaName'],
            },
        ),
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='token')),
                ('muser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.manager')),
                ('suser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.student')),
                ('tuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('SubNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='提交编号')),
                ('Ans', models.CharField(blank=True, max_length=50, null=True, verbose_name='学生答案')),
                ('Score', models.FloatField(verbose_name='作业成绩')),
                ('SubTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('HomeNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.homework', verbose_name='作业编号')),
            ],
            options={
                'ordering': ['-SubTime'],
            },
        ),
        migrations.AddField(
            model_name='sign',
            name='sign_by',
            field=models.ManyToManyField(related_name='students', to='job.student', verbose_name='需要进行此签到的学生'),
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('QuesNo', models.IntegerField(primary_key=True, serialize=False, verbose_name='题号')),
                ('Cont', models.CharField(max_length=5000, verbose_name='题目')),
                ('CorAns', models.CharField(max_length=5000, verbose_name='题目答案')),
                ('HomNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.homework', verbose_name='作业id')),
            ],
            options={
                'ordering': ['-QuesNo'],
            },
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoticeTitle', models.CharField(default='通知标题', max_length=60, verbose_name='通知标题')),
                ('NoticeContent', models.CharField(default='通知内容', max_length=5000, verbose_name='通知内容')),
                ('NoticePubTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知发布时间')),
                ('MaNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.manager', verbose_name='发布此通知的管理员编号')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='StuNo',
            field=models.ManyToManyField(related_name='courses', to='job.student', verbose_name='选修这门课程的学生学号'),
        ),
        migrations.AddField(
            model_name='course',
            name='TeaNo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.teacher', verbose_name='上这门课程的教师编号'),
        ),
    ]
